services:
  postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - collab-network

  redis:    
    image: redis:7-alpine
    container_name: auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - collab-network

  app:
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    container_name: go-auth
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DBNAME: ${PG_DBNAME}
      TOKEN_SECRET: ${TOKEN_SECRET}
      DB_MAX_CONNS: ${DB_MAX_CONNS}
      DB_CONN_TIMEOUT: ${DB_CONN_TIMEOUT}
      MIGRATIONS_PATH: ${MIGRATIONS_PATH}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      USER_SERVICE_ADDR: collab-user-service:60052
      OAUTH_GOOGLE_CLIENT_ID: ${OAUTH_GOOGLE_CLIENT_ID}
      OAUTH_GOOGLE_CLIENT_SECRET: ${OAUTH_GOOGLE_CLIENT_SECRET}
      OAUTH_GITHUB_CLIENT_ID: ${OAUTH_GITHUB_CLIENT_ID}
      OAUTH_GITHUB_CLIENT_SECRET: ${OAUTH_GITHUB_CLIENT_SECRET}
      OAUTH_FRONTEND_CALLBACK_URL: ${OAUTH_FRONTEND_CALLBACK_URL}
      OAUTH_BACKEND_BASE_URL: ${OAUTH_BACKEND_BASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations
      - ./config:/app/config
    networks:
      - collab-network
    ports:
      - "60051:60051"  # gRPC
      - "8081:8080"    # HTTP REST Gateway (Внешний 8081 -> Внутренний 8080)
    command: >
      sh -c "
        /app/migrate up &&
        /app/go-auth
      "
networks:
  collab-network:
    name: collab-network
    driver: bridge
    external: true

volumes:
  postgres_data:
  redis_data:
