services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - collab-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - collab-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-auth
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DBNAME: db_auth
      TOKEN_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      DB_MAX_CONNS: 5
      DB_CONN_TIMEOUT: 30s
      MIGRATIONS_PATH: /app/migrations
      REDIS_HOST: redis
      REDIS_PORT: 6379
      USER_SERVICE_ADDR: collab-user-service:60052
      OAUTH_GOOGLE_CLIENT_ID: ${OAUTH_GOOGLE_CLIENT_ID}
      OAUTH_GOOGLE_CLIENT_SECRET: ${OAUTH_GOOGLE_CLIENT_SECRET}
      OAUTH_GITHUB_CLIENT_ID: ${OAUTH_GITHUB_CLIENT_ID}
      OAUTH_GITHUB_CLIENT_SECRET: ${OAUTH_GITHUB_CLIENT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations
      - ./config:/app/config
    ports:
      - "60051:60051"  # gRPC
      - "8081:8080"    # HTTP REST Gateway (Internal 8080 from config.yaml)
    command: >
      sh -c "
        /app/migrate up &&
        /app/go-auth
      "
    networks:
      - collab-network

networks:
  collab-network:
    name: collab-network
    driver: bridge
    external: true

volumes:
  postgres_data:
  redis_data:
